services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: encoder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbit:
    image: "rabbitmq:management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  encoder-go:
    build: ./encoder-go
    volumes:
      - ./encoder-go:/go/src
    working_dir: /go/src
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/encoder_go?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  encoder-rust:
    build:
      context: ./encoder-rust
      target: builder
    volumes:
      - ./encoder-rust:/usr/src/app
    working_dir: /usr/src/app
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/encoder_rust?sslmode=disable"
      PATH: "/opt/bento4/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
