FROM golang:1.25-alpine AS build-env

RUN apk add --update --upgrade build-base

WORKDIR /go/src
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" framework/cmd/server/server.go

FROM alpine:3.21

RUN apk add --no-cache ca-certificates ffmpeg bash python3 libc6-compat libstdc++ libgcc

ENV BENTO4_PATH="/opt/bento4"
RUN wget -q https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-641.x86_64-unknown-linux.zip && \
    unzip Bento4-SDK-1-6-0-641.x86_64-unknown-linux.zip && \
    mv Bento4-SDK-1-6-0-641.x86_64-unknown-linux ${BENTO4_PATH} && \
    rm Bento4-SDK-1-6-0-641.x86_64-unknown-linux.zip && \
    apk del wget unzip 2>/dev/null; true

ENV PATH="${BENTO4_PATH}/bin:${PATH}"

WORKDIR /app
COPY --from=build-env /go/src/server .

ENTRYPOINT ["./server"]
